apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  labels:
    role: sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      role: sample-app
  template:
    metadata:
      labels:
        role: sample-app
    spec:
      containers:
      - name: sample-app
        image: vincmarz/go-http-server:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
